name: Update Packages

on:
  push:
    branches: [main]

jobs:
  CR:
    name: "Build And Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Release
        run: yarn release
    env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}